"""data error on name constraiints

Revision ID: 76e4070bb8c4
Revises: d5a7bbe293bb
Create Date: 2023-08-23 17:46:34.697829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e4070bb8c4'
down_revision: Union[str, None] = 'd5a7bbe293bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
