"""add to databse books

Revision ID: d5a7bbe293bb
Revises: 05e3f8aac3a3
Create Date: 2023-08-23 17:38:02.957040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a7bbe293bb'
down_revision: Union[str, None] = '05e3f8aac3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('book_title')
    )
    op.drop_table('book_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_list',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('book_title', sa.VARCHAR(), nullable=True),
    sa.Column('publisher', sa.VARCHAR(length=55), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('book_title')
    )
    op.drop_table('books')
    # ### end Alembic commands ###
